kind: List
apiVersion: v1
items:

- kind: Deployment
  apiVersion: apps/v1beta1
  metadata:
    labels:
      name: kuill
    name: kuill
    namespace: kube-system
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: kuill
    template:
      metadata:
        labels:
          name: kuill
          service: kuill
      spec:
        serviceAccount: kuill-serviceaccount
        volumes:
        - name: auth-proxy-certs
          secret:
            secretName: auth-proxy-certs
        containers:
        - image: mattdeboer/kuill
          name: kuill
          volumeMounts: 
          - name: auth-proxy-certs
            mountPath: /certs
            readOnly: true
          env:
          - name: KUILL_PORT
            value: "8443"
          - name: KUILL_ANONYMOUS_GROUPS
            value: system:masters
          - name: KUILL_SERVER_CERT
            value: /certs/auth-proxy.pem
          - name: KUILL_SERVER_KEY
            value: /certs/auth-proxy-key.pem
          - name: KUILL_KUBERNETES_CLIENT_CERT
            value: /certs/auth-proxy.pem
          - name: KUILL_KUBERNETES_CLIENT_KEY
            value: /certs/auth-proxy-key.pem
          - name: KUILL_KUBERNETES_CLIENT_CA
            value: /certs/ca.pem
          - name: KUILL_VERBOSE
            value: "true"
          - name: KUILL_TRACE_REQUESTS
            value: "true"
          ports:
          - containerPort: 8443
            name: https
        
- kind: Service
  apiVersion: v1
  metadata:
    name: kuill
    namespace: kube-system
  spec:
    ports:
    - name: kuill
      port: 8443
      targetPort: 8443
      nodePort: 30443
    selector:
      name: kuill
    type: NodePort
