kind: List
apiVersion: v1
items:
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: cluster-reader
  subjects:
    - kind: User
      name: reader
    
  roleRef:
    kind: ClusterRole
    name: view
    apiGroup: "rbac.authorization.k8s.io"

