apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: ${app}
  name: ${name}
  namespace: ${namespace}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ${app}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${app}
    spec:
      containers:
        - image: ${docker_image}
          imagePullPolicy: IfNotPresent
          name: ${name}
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          env:
            - name: VAR_1
              value: "some value" 
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30