apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ${app}
  name: ${name}
  namespace: ${namespace}
spec:
  containers:
    - image: ${docker_image}
      imagePullPolicy: IfNotPresent
      name: ${app}
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  securityContext: {}
  terminationGracePeriodSeconds: 30

