apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ${name}
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${role_name}
subjects:
# remove or copy as needed
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: ${group_name}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${user_name}
  - apiGroup: rbac.authorization.k8s.io
    kind: ServiceAccount
    name: ${service_account_name}
    namespace: ${service_account_namespace}